### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by mdavezac** [jabirali/bodge#1]
For publishing with JOSS (openjournals/joss-reviews#7134), bodge will require community guidelines. The exact format is not mandated AFAIK, but many authors include a CONTRIBUTING file, as per https://docs.github.com/en/site-policy/github-terms/github-community-guidelines.

**Comment by jabirali** [comment]
Thanks for the suggestion! I have now pushed a [CONTRIBUTING.md](https://github.com/jabirali/bodge/blob/main/CONTRIBUTING.md) file to the `main` branch, please have a look if it looks clear or could be further improved.

**Comment by jabirali** [comment]
Closing this as completed, but feel free to reopen or add further comments.
